fix_マイページ関連_ユーザ情報編集_メール送信
KyoheiYamamoto/flatstyle pull request #10
Opened 2021-01-10 02:35 UTC by Sasaki1994m

最新情報をpullし直しました。（修正内容は変わっておりません。）

ーーーーーーーーーーーーーーーー
マイページ関連の実装をしました。
①ユーザー情報の編集（名前・メール）バリデーション処理。
②ランクアップ申請。依頼内容を記載の上送信すると、gmailのメールに届きます。
（テストは2,3回まででお願いします。）
③会員一覧の表示。リスト一覧から編集を押すと削除画面（削除処理は未実装です。）
ユーザ情報が変更できるか。
バリデーションがかかっているか。
メールが送れているか。（到着したらslackで知らせます。）
会員一覧から情報を取得できているか確認願います。
ーーーーーーーーーーーーーーーー

追加で.envファイルのメールドライバーを変更願います。
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=465
MAIL_USERNAME=bis045970@gmail.com
MAIL_PASSWORD=xsxfxiolydwifcfe
MAIL_ENCRYPTION=ssl

2021-01-10 13:47 UTC, ryota100 commented
実装お疲れ様です。

22時半ごろにランクアップのメール送信したので確認いただけると幸いです。

２点だけ、指摘がありまして、
①不意に１行空いてたり、2行空いてたりというのが少し目立ったかなというように感じたので、今回はそこまでシビアなものではないかと思うのですが、最近レビューいろんな人のをよく見るので、行間の意識をされるとよりいいのかなと思いました。

③の会員一覧の表示について、テーブルからのデータで表示がされなかったので、気になりました。今回はそこまでの実装ではないということであれば問題ありません。

以上、よろしくお願いします。

2021-01-11 08:27 UTC, KyoheiYamamoto commented on app/Http/Controllers/MypageController.php
> +    public function rankup_confirm(MypageRequest $request){
rankup_confirmこちらのメソッド名はキャメルケースで記載をお願いします。
rankupConfirmみたいな感じで

2021-01-11 08:29 UTC, KyoheiYamamoto commented on app/Http/Requests/MypageRequest.php
> +    }
りょうたさんも仰っておりますがここの開業は不要ですね

2021-01-11 08:36 UTC, KyoheiYamamoto commented on app/Mail/RequestMail.php
> +    public function __construct($name,$email,$comment)
カンマと引数の間にスペースを入れてくれたら読みやすくなります

2021-01-11 08:44 UTC, KyoheiYamamoto requested changes
@Sasaki1994m 
実装お疲れ様でした！私の方でも動作確認と正常にdevelopにmergeされている部分も確認しました。
ランクアップ申請画面でわかりやすいメッセージを送っていますのでご確認ください
僕の方からはりょうたさんも指摘している部分記述方法については
下記URLを確認してみてください（今後も必ず使うと思いますので〜）
https://www.ritolab.com/entry/92

2021-01-13 04:47 UTC, KyoheiYamamoto approved these changes

2021-01-13 05:13 UTC, KyoheiYamamoto commented
私の方で動作確認しました！マイページにもアクセスでき、ユーザー名を変えてもphpMyAdminの方でしっかりと記録を
残っていたので私の方では大丈夫です！

2021-01-13 11:14 UTC, ryota100 commented
回答遅れました。
問題ありません。
よろしくお願いします。

2021-01-13 12:07 UTC, merged