Feature/makoto fix mypage view
KyoheiYamamoto/flatstyle pull request #14
Opened 2021-01-24 12:32 UTC by Sasaki1994m

マイページ関連の修正をしました。
①パスワードリセット
→パスワードリセット時の新しいパスワード入力を８文字以上から６文字以上に変更しました。
②会員一覧
→会員一覧の権限を見える化しました。登録日の欄も設けているので一度登録してもらい実際に出力されているか
確認願います。（時間もUTC→東京の時間に合わせています。）
③マイページ画面
→りょうたんさんが実装してくれた、今自分がどの権限を持っているのかのの表示を調整しました。

2021-01-25 15:02 UTC, ryota100 commented
実装お疲れ様です😊
挙動など確認しました。
会員一覧もしっかり表示され問題ありません。
よろしくお願いします。

2021-01-26 07:08 UTC, KyoheiYamamoto requested changes
>①パスワードリセット
→パスワードリセット時の新しいパスワード入力を８文字以上から６文字以上に変更しました。
②会員一覧
→会員一覧の権限を見える化しました。登録日の欄も設けているので一度登録してもらい実際に出力されているか
確認願います。（時間もUTC→東京の時間に合わせています。）
③マイページ画面
→りょうたんさんが実装してくれた、今自分がどの権限を持っているのかのの表示を調整しました。

私の方で挙動の方も確認しました
問題なく時刻も表示されていました。
私の方ではすこし気になる部分があったのでそこを修正していただければ幸いです

2021-01-27 01:33 UTC, KyoheiYamamoto approved these changes

2021-01-27 01:35 UTC, KyoheiYamamoto commented
@Sasaki1994m さん
修正ありがとうございました！
こちら私の方でmergeしておきますね

2021-01-27 01:35 UTC, merged